config/routes.rb
Rails.application.routes.draw do
  resources :postings

  root 'postings#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/posting.rb
class Posting < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/postings_controller.rb
class PostingsController < ApplicationController
  before_action :set_posting, only: [:show, :edit, :update, :destroy]

  # GET /postings
  # GET /postings.json
  def index
    @postings = Posting.all
  end

  # GET /postings/1
  # GET /postings/1.json
  def show
  end

  # GET /postings/new
  def new
    @posting = Posting.new
  end

  # GET /postings/1/edit
  def edit
  end

  # POST /postings
  # POST /postings.json
  def create
    @posting = Posting.new(posting_params)

    respond_to do |format|
      if @posting.save
        format.html { redirect_to @posting, notice: 'Posting was successfully created.' }
        format.json { render :show, status: :created, location: @posting }
      else
        format.html { render :new }
        format.json { render json: @posting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /postings/1
  # PATCH/PUT /postings/1.json
  def update
    respond_to do |format|
      if @posting.update(posting_params)
        format.html { redirect_to @posting, notice: 'Posting was successfully updated.' }
        format.json { render :show, status: :ok, location: @posting }
      else
        format.html { render :edit }
        format.json { render json: @posting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /postings/1
  # DELETE /postings/1.json
  def destroy
    @posting.destroy
    respond_to do |format|
      format.html { redirect_to postings_url, notice: 'Posting was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_posting
      @posting = Posting.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def posting_params
      params.require(:posting).permit(:user_name, :text)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/postings_helper.rb
module PostingsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sugita</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/postings/_form.html.erb
<%= form_for(posting) do |f| %>
  <% if posting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(posting.errors.count, "error") %> prohibited this posting from being saved:</h2>

      <ul>
      <% posting.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions posting-submit">
    <%= f.submit '投稿' %>
  </div>

  <div class="field posting-user-name">
    <%= f.label :user_name, '投稿者名' %>
    <%= f.text_field :user_name %>
  </div>

  <div class="field posting-text">
    <%= f.text_area :text %>
  </div>

<% end %>

app/views/postings/edit.html.erb
<h1>Editing Posting</h1>

<%= render 'form', posting: @posting %>

<%= link_to 'Show', @posting %> |
<%= link_to 'Back', postings_path %>

app/views/postings/index.html.erb
<div class='posting-index'>
  <p id="notice"><%= notice %></p>

  <h1>杉さん掲示板</h1>

  <table>

    <tbody>
      <% @postings.each do |posting| %>
        <tr>
          <td class='title'>
            <%= posting.id %>
            ：
            <span class='user-name'><%= posting.user_name %></span>
            ：
            <%= posting.created_at %>
          </td>
        </tr>
        <tr>
          <td class='text'><%= posting.text %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to '書き込む', new_posting_path, class: 'new-posting' %>
</div>

app/views/postings/new.html.erb
<h1>投稿画面</h1>

<%= render 'form', posting: @posting %>

<%= link_to '戻る', postings_path, class: 'back' %>

app/views/postings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User name:</strong>
  <%= @posting.user_name %>
</p>

<p>
  <strong>Text:</strong>
  <%= @posting.text %>
</p>

<%= link_to 'Edit', edit_posting_path(@posting) %> |
<%= link_to 'Back', postings_path %>